### PR TITLE
Major Update to Keys Plugin

### PR DESCRIPTION
**Pull request by azdle**
Supports adding, deleting, and printing CIKs to(/from) your exoline config file.

Does not yet support the suggested trim command.

### CODE REVIEW

**Comment by azdle** [comment]
Added clean command to remove non-existing CIKs from list.

**Comment by dweaver** [comment]
You want me to wait to pull this in, or should I go ahead?

**Comment by azdle** [comment]
I think we should go ahead and pull it in. It doesn't use the proper submodule stuff (because I didn't know that was a thing when I started), but it does work.

Also, I just realized that I never added the better yaml library to the requirements.txt

**Comment by dweaver** [comment]
I think we should have some tests for this before we pull it. That will catch things like the missing yaml library in requirements.txt. Let me know if you want help getting a test in.

**Comment by azdle** [comment]
Are there any tests for any of the other plugins that I can use as an example? I'm not seeing anything.

**Comment by dweaver** [comment]
They're mixed in with main exoline tests, unfortunately. Here's a recent one for move:

https://github.com/exosite/exoline/blob/master/test/test.py#L2582

**Pull request merged**
